version: '3'

services:
  app:
    image: 'boilerplate-mern'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: 'development'
    environment:
      NODE_APP_INSTANCE: 'docker'
      NODE_CONFIG_ENV: 'e2e'
      NODE_ENV: 'e2e'
    command: 'npm run e2e:ci'
    depends_on:
      - db

  db:
    image: mongo:5.0
    ports:
      - '27017:27017'
